### ISSUE TITLE
Source code of the doc

### ISSUE THREAD

**Issue by noraj** [Syslifters/sysreptor-docs#1]
Seems like only the build is available on the repository branch gh-pages, not the source code.

Nowadays it's easy to have the source code on the main branch and auto-build and auto-deploy to github pages using a github action CI/CD template.

Having the source code of the website would allow community contributions to the doc.

**Comment by Lednerb** [comment]
This would be a nice addition, because there are some small issues that I was going to fix for you @aronmolnar, @MWedl, @mlec1  ;-)

**Comment by aronmolnar** [comment]
Great. We'll do

**Comment by aronmolnar** [comment]
We published the source of the docs here: https://github.com/Syslifters/sysreptor/tree/main/docs
:)
